config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , :controllers => {registrations: "registrations"}

  root 'top#index'

  resources :users, only: [:show, :edit, :update]

  resources :prototypes, only: [:new, :create]

  resources :prototypes, only: [:show] do
    resources :comments, only: [:create], module: 'prototypes'
    member do
      put 'like'    => 'prototypes#like'
      put 'dislike' => 'prototypes#dislike'
    end
  end

  resources :tags, only: [:index, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :main_image, AvatarUploader
  mount_uploader :sub_image_1, AvatarUploader
  mount_uploader :sub_image_2, AvatarUploader
  mount_uploader :sub_image_3, AvatarUploader
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  acts_as_taggable
  acts_as_votable

  has_one :image
  accepts_nested_attributes_for :image

  has_many   :comments
  belongs_to :user

  validates :title, :catch_copy, :concept, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter

  mount_uploader :avatar, AvatarUploader

  has_many :comments
  has_many :prototypes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:user_name, :member_of, :profile, :works, :avatar]
  end
end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController
  def create
    @prototype = Prototype.find(params[:prototype_id])
    @prototype.comments.create(comment_params)
    @comments  = @prototype.comments
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def show
    @prototype = Prototype.find(params[:id])
    @comment   = Comment.new
    @comments  = @prototype.comments
    @tags      = @prototype.tag_list
  end
  def new
    @prototype = Prototype.new
  end
  def create
    @prototype = current_user.prototypes.new(prototype_params)
    if @prototype.save
      redirect_to root_url, notice: "Complete!"
    else
      redirect_to new_prototype_url, notice: "you need to fill requisite datas"
    end
  end

  def like
    @prototype = Prototype.find(params[:id])
    @prototype.liked_by current_user
  end

  def dislike
    @prototype = Prototype.find(params[:id])
    @prototype.disliked_by current_user
  end

  private
  def prototype_params
    tag_list = params[:prototype][:tag_list].join(",")
    params.require(:prototype).permit(:title,
                                      :catch_copy,
                                      :concept,
                                      image_attributes: [:main_image,
                                        :sub_image_1,
                                        :sub_image_2,
                                        :sub_image_3])
                              .merge(tag_list: tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags       = Tag.all
  end

  def show
    @tag        = Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag.name).page(params[:page]).per(4)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @prototypes = Prototype.order("created_at DESC").page(params[:page]).per(4)
    @four_hot_prototypes = Prototype.order("created_at ASC").page(params[:page]).per(4)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  def new
  end
  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user       = User.find(params[:id])
    @prototypes = @user.prototypes
                       .order(created_at: :DESC)
                       .page(params[:page]).per(4)
  end

  def edit
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:user_name,
                                 :avatar,
                                 :email,
                                 :member_of,
                                 :profile,
                                 :works)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_of_created(prototype)
    "#{ prototype.created_at.month } , #{ prototype.created_at.day }"
  end

  def tag_id(tag)
    Tag.where(name: "#{ tag }")[0].id
  end
end

app/helpers/prototypes/comments_helper.rb
module Prototypes::CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
  def by_whom?
    @prototype.user.user_name
  end

  def sub_image(number)
    if number == 1
      @prototype.image.sub_image_1
    elsif number == 2
      @prototype.image.sub_image_2
    else
      @prototype.image.sub_image_3
    end
  end

  def creater_path
    "/users/#{ @prototype.user_id }"
  end

  def affiliation
    @prototype.user.member_of
  end

  def creater_avatar
    "#{ @prototype.user.avatar }"
  end

  def like_size
    @prototype.get_likes.size
  end

  def commenter_avatar(comment)
    "#{ comment.user.avatar }"
  end

  def commenter(comment)
    comment.user.user_name
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
  def by_whom?(prototype)
    prototype.user.user_name
  end

  def main_image(prototype)
    prototype.image.main_image
  end
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      = unless user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              %a{href: new_user_session_path}
                Get Started
      = if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.user_name
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "Profile Edit", edit_user_path(current_user.id)
              %li
                = link_to "Logout", destroy_user_session_path, method: "delete"
          %li
            .btn.btn-primary.navbar-btn
              %a{href: "/prototypes/new"}
                New Proto

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{src: "/assets/protospace.js"}
    / %script{src: "http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"}
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/prototypes/_comment.html.haml
.col-md-8
  .media
    .media-left
      %a{ href: "#" }
        %img.media-object{ alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: commenter_avatar(comment), style: "width: 64px; height: 64px;" }/
    .media-body
      %h4#top-aligned-media.media-heading
        #{ commenter(comment) }
        %a.anchorjs-link{ href: "#top-aligned-media" }
          %span.anchorjs-icon
      %p #{ comment.comment }

app/views/prototypes/_form.html.haml
.row.proto-comments
  %h4.col-md-12
    Comments
    %span.num (#{ @comments.length })
    .comments
      = render partial: 'comment', collection: @comments
  .col-md-8
    .form-inline
      = form_for([@prototype, @comment], remote: true) do |f|
        - if signed_in?
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :comment, placeholder: "Your comments", rows: "3", class: "comment_form"
            .form-group.col-md-2
              %button.btn.btn-primary Comment

app/views/prototypes/_like_button.html.haml
.col-md-6.text-right
  - if signed_in?
    - unless current_user.liked? @prototype
      %button.btn.btn-default
        = image_tag("icon_heart.svg")
        = link_to("LIKE!", like_prototype_path(@prototype), method: :put, remote: true)
        %span.num
          = like_size
    - else
      %button.btn.btn-default
        = image_tag("fuckfacebook.png")
        = link_to("LIKE!", dislike_prototype_path(@prototype), method: :put, remote: true)
        %span.num
          = like_size
  - else
    %button.btn.btn-default
      = image_tag("icon_heart.svg")
      LIKE!
      %span.num
        = like_size

app/views/prototypes/_tag.html.haml
%lis
  %a{ href: "/tags/#{ tag_id(tag) }", class: "btn btn-default" } #{ tag }

app/views/prototypes/comments/create.js.erb
$(".comment_form").val('');
$(".comments").html('<%=j render partial: "/prototypes/comment", collection: @comments %>');
$(".num").html('<%= "(#{ @comments.length })" %>')

app/views/prototypes/create.html.haml
.row-form
  .col-lg-12
    %h3 Mission Complete !
    = link_to 'Home', root_path

app/views/prototypes/dislike.js.erb
$(".like_button").html('<%=j render partial: "prototypes/like_button" %>');

app/views/prototypes/like.js.erb
$(".like_button").html('<%=j render partial: "prototypes/like_button" %>');

app/views/prototypes/new.html.haml
.container.proto-new
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
    = form_for(@prototype) do |f|
      .col-md-12
        = if flash[:notice]
          .alert.alert-danger
            = flash[:notice]
        = f.text_field :title, autofocus: true, placeholder: "Title"
      .row
        = f.fields_for :image, @prototype.image || Image.new do |i|
          .col-md-12
            .cover-image-upload
              = i.file_field :main_image
          .col-md-12
            %ul.proto-sub-list.list-group
              %li.list-group-item.col-md-4
                .image-upload
                  = i.file_field :sub_image_1
              %li.list-group-item.col-md-4
                .image-upload
                  = i.file_field :sub_image_2
              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch copy"
        .col-md-12
          = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = f.label :web_design, placeholder: "Web Design"
              = text_field_tag 'prototype[tag_list][]', nil
            .col-md-3
              = f.label :UI, placeholder: "UI"
              = text_field_tag 'prototype[tag_list][]', nil
            .col-md-3
              = f.label :application, placeholder: "Application"
              = text_field_tag 'prototype[tag_list][]', nil
      .row.text-center.proto-btn
        %button.actions.btn.btn-lg.btn-primary.btn-block
          Publish

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    = if flash[:notice]
      .alert.alert-success
        = flash[:notice]
    .col-md-6
      .media
        .media-left
          %a{ href: "#" }
            %img.media-object{ alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: creater_avatar, style: "width: 64px; height: 64px;" }/
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            %a{ href: creater_path } by #{ by_whom?(@prototype) }
            %span.degree #{ affiliation }
    .like_button
      = render 'like_button'
  .row
    .col-md-9
      = image_tag("#{ @prototype.image.main_image.url.to_s }", class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        %li.list-group-item
          = image_tag("#{ sub_image(1) }", class: 'img-responsive')
        %li.list-group-item
          = image_tag("#{ sub_image(2) }", class: 'img-responsive')
        %li.list-group-item
          = image_tag("#{ sub_image(3) }", class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p #{ @prototype.catch_copy }
    .col-md-6
      %h4 Concept
      %p #{ @prototype.concept }
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        = render partial: 'tag', collection: @tags
  = render 'form'

app/views/tags/index.html.haml
.tag_list
  - @tags.each do |tag|
    %lis
      %a{ href: "/tags/#{ tag.id }", class: "btn btn-default btn-lg" } #{ tag.name }

app/views/tags/show.html.haml
.filter-nav
  .container
    = if flash[:notice]
      .alert.alert-success
        = flash[:notice]
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          %a{ class: 'show_popular' } Tagged With "#{ @tag.name }"

.container.proto-list
  .row#prototypes
    = render partial: 'top/prototype', collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled#prototypes
      = paginate(@prototypes)

app/views/top/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    %a{ href: "/prototypes/#{ prototype.id }" }
      = image_tag "#{ main_image(prototype) }"
      .caption
        %h3
          = prototype.title
        .proto-meta
          .proto-user
            %a{ href: "/users/#{ prototype.user.id }" }
              by #{ by_whom?(prototype) }
          .proto-posted
            = date_of_created(prototype)
        %ul.proto-tag-list.list-inline
          - prototype.tag_list.each do |tag|
            %li
              %a{ href: "/tags/#{ tag_id(tag) }", class: "btn btn-default" } #{ tag }

app/views/top/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    = if flash[:notice]
      .alert.alert-success
        = flash[:notice]
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          %a{ class: 'show_popular' } PROTOTYPES
        %li{ role: "presentation" }
          %a{ class: 'show_newest' } 4 HOTTEST PROTO
      %a{ class: "btn btn-default col-lg-1", href: "/tags" } View Tags

.container.proto-list
  .row#prototypes
    = render partial: 'prototype', collection: @prototypes
  .row#newest-prototypes{ style: "display: none" }
    = render partial: 'prototype', collection: @newest_prototypes
.text-center
  %ul.pagination
    %li.disabled#prototypes
      = paginate(@prototypes)

app/views/users/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    %a{ href: "/prototypes/#{ prototype.id }" }
      = image_tag("#{ main_image(prototype) }")
      .caption
        %h3 #{ prototype.title }
        .proto-meta
          .proto-date
            = date_of_created(prototype)
        %ul.proto-tag-list.list-inline
          - prototype.tag_list.each do |tag|
            %li
              %a{ href: "#", class: "btn btn-default" } #{ tag }

app/views/users/edit.html.haml
.container.user-new
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Edit Profile
        = form_for(current_user) do |f|
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :user_name
            .user-image.col-md-2{style: "background-image: url(#{current_user.avatar})"}
              %button.btn.btn-primary Change image
              = f.file_field :avatar
          = f.text_field :email
          .col-md-12
            %h4 Member of
            .user-user-member.row
              .user-name.col-md-12
                = f.text_field :member_of
            %h4 Profile
            .user-user-profile.row
              .user-name.col-md-12
                = f.text_area :profile, cols: "30", rows: "4"
            %h4 Works 
            .user-name_image.row
              .user-name.col-md-12
                = f.text_area :works, cols: "30", rows: "4"
            %button.actions.btn.btn-lg.btn-primary.btn-block
              Save
      

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{ href: "#" }
          %img.media-object{ alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: "#{ @user.avatar }", style: "width: 64px; height: 64px;" }/
      .media-body
        %h4#top-aligned-media.media-heading
          #{ @user.user_name }
          %span.label.label-default.project-number
            #{ @user.prototypes.length }
            %i Projects
        .proto-user
          %span.degree #{ @user.member_of }
        .row
          .col-md-6
            %h4 Profile
            %p #{ @user.profile }
          .col-md-6
            %h4 Works
            %p #{ @user.works }
.container.proto-list
  .row
    = render partial: 'prototype', collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled
      = paginate(@prototypes)

app/views/users/update.html.haml
.row-form
  .col-lg-12
    %h3 Upadate is Complete!
    = link_to 'Home', root_path